### ISSUE TITLE
How to install the addon?

### ISSUE THREAD

**Issue by Magzhan8** [cuba-platform/cuba-dnd#3]
I have some troubles with installing the addon. I download and open it as project in Studio, when i try to add it in my main project as Custom component, I get error that artifact not found

**Comment by jreznot** [comment]
Check this guide: https://github.com/cuba-platform/cuba-dnd#step-by-step-guide

Use version that is compatible with your platform version: https://github.com/cuba-platform/cuba-dnd#compatibility-with-platform-versions

In the simplest case, you just add `com.haulmont.addon.dnd:cuba-dnd-global:1.2.0` (for CUBA 6.8) as custom application component using CUBA Studio.

**Comment by Magzhan8** [comment]
Yes it was a problem with Cuba version. But still can't use cuba-dnd. Because in my Controller i use DDVerticalLayout, which imported as fi.jasoft.dragdroplayouts.DDVerticalLayout, no options with com.haulmont.addon.dnd.components.
